name: Build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish Avalonia
        run: |
          dotnet publish MusicDecrypto.Avalonia/MusicDecrypto.Avalonia.csproj -c Release -r win-x64 --sc -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=partial -o ./gui-x64

      - name: Publish CLI
        run: |
          dotnet publish MusicDecrypto.Commandline/MusicDecrypto.Commandline.csproj -c Release -r win-x64 -o ./cli-x64

      - name: Pack
        run: |
          7z a musicdecrypto-gui-win-x64.7z .\gui-x64\*
          7z a musicdecrypto-cli-win-x64.7z .\cli-x64\musicdecrypto.exe
          (Get-FileHash musicdecrypto-gui-win-x64.7z SHA256).Hash + " musicdecrypto-gui-win-x64.7z" > musicdecrypto-gui-win-x64.7z.sha256
          (Get-FileHash musicdecrypto-cli-win-x64.7z SHA256).Hash + " musicdecrypto-cli-win-x64.7z" > musicdecrypto-cli-win-x64.7z.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: musicdecrypto
          path: |
            ./musicdecrypto-gui-win-x64.7z
            ./musicdecrypto-cli-win-x64.7z
            ./musicdecrypto-gui-win-x64.7z.sha256
            ./musicdecrypto-cli-win-x64.7z.sha256
